### ISSUE TITLE
MC simu. FCAL gains calibration and energy dependence correction appear wrong

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/halld_sim#121]
ccdb ls /FCAL/gains shows no mc variation but ccdb dump /FCAL/gains::mc output what seems to be un-realistic gains, to illustrate that I am plotting the mean distribution of the gammagamma invariant mass of pi0 shooted with the particle gun vs. ring number
![image](https://user-images.githubusercontent.com/22524742/80318164-10090880-87d6-11ea-80f2-60b90256f035.png)

AND

energy dependence correction appears to make things worse.
 To illustrate that I am plotting the fitted pi0 mean divided by the pi0 PDG mass vs the photon momentum when the photon momentum difference between the pi0 decay photons is below 100MeV vs ring number 

![image](https://user-images.githubusercontent.com/22524742/80318218-93c2f500-87d6-11ea-999b-c0e82bc9a518.png)
![image](https://user-images.githubusercontent.com/22524742/80318233-be14b280-87d6-11ea-9e8f-f94c68bd8c27.png)
![image](https://user-images.githubusercontent.com/22524742/80318243-d2f14600-87d6-11ea-83a4-3f41a5657cf7.png)
![image](https://user-images.githubusercontent.com/22524742/80318257-ef8d7e00-87d6-11ea-93f1-b2cd9fb5c9ca.png)

**Comment by sdobbs** [comment]
What run number are you using to make these simulations?

**Comment by igjaegle** [comment]
PrimEX-D but it should not matter as the gains table is the same for all runs and the energy dependence correction is the same for all runs

**Comment by igjaegle** [comment]
ccdb ls FCAL/shower_calib_piecewise
/FCAL/shower_calib_piecewise
(ID)   (Created)              (Modified)              (variation)     (run range)      (comments)
 256682  2020-04-03 15-02-08    2020-04-03 15-02-08     default         71592L-79999L   
 256681  2020-04-03 15-01-51    2020-04-03 15-01-51     default         71461L-71591L   
 256680  2020-04-03 15-01-20    2020-04-03 15-01-20     default         70000L-71460L   
 253898  2020-03-30 14-15-55    2020-03-30 14-15-55     default         61321L-61956L   
 253584  2020-03-24 11-29-06    2020-03-24 11-29-06     default         70000L-79999L   
 230591  2020-01-17 13-15-14    2020-01-17 13-15-14     default         70000L-inf      
 228869  2019-11-25 15-18-36    2019-11-25 15-18-36     default         60000L-61507L   
 228867  2019-11-20 13-55-38    2019-11-20 13-55-38     default         61508L-69999L   
 228866  2019-11-20 13-55-18    2019-11-20 13-55-18     default         60000L-61507L   
 224332  2019-07-29 09-49-12    2019-07-29 09-49-12     mc              0L-inf

**Comment by igjaegle** [comment]
and for the gains, there is no mc variation only ccdb dump FCAL/gains::mc output something

**Comment by sdobbs** [comment]
Right, so HDGeant4 outputs objects on the calibrated hit level, which then have some smearing applied.  The gains are not used, except indirectly, to model the effect of the readout thresholds.

The run numbers matter, so if I compare the output of "ccdb dump /FCAL/gains:61321" and "ccdb dump /FCAL/gains:61321:mc", at first glance I am seeing the same data.

I presume all these pi0's have the same vertex, or you're otherwise correctly dealing with the fact that there's no vertex information in these events.

It's good that you're looking at this position dependence of the calibration, since that had not yet been done.  These results are a little surprising, but the non-linear energy calibration was only tuned with a photon gun.  So, we should check to make sure that the photon gun is still giving the correct answer.  If the single photon energies are correct, presumably it's the shower position determination that is causing this problem.

**Comment by igjaegle** [comment]
This is exactly the problem. There is no mc variation for the gains which is why 
ccdb dump /FCAL/gains:xxxxx and ccdb dump /FCAL/gains:xxxxx:mc give the same output. Even if one set JANA_CALIB_CONTEXT variation=mc, it will read the default gains which corresponds to the data gain and it is why there is a run dependence! This is wrong. We need a gain table for the simulation even if it is only 1 or change src/libraries/FCAL/DFCALHit_factory.cc.  

In principle, FCAL is so far away from the target that the vertex position does not matter in fact (see HDGEANT4#146, I did only observe a vertex position dependence for BCAL). In short, the FCAL energy calibration has no obvious vertex position dependence.

**Comment by mashephe** [comment]
Hi Igal,

On Apr 26, 2020, at 10:24 PM, igjaegle <notifications@github.com<mailto:notifications@github.com>> wrote:

This is exactly the problem. There is no mc variation for the gains which is why
ccdb dump /FCAL/gains:xxxxx and ccdb dump /FCAL/gains:xxxxx:mc give the same output. Even if one set JANA_CALIB_CONTEXT variation=mc, it will read the default gains which corresponds to the data gain and it is why there is a run dependence! This is wrong. We need a gain table for the simulation.

It is not wrong -- it is the logical algorithm for simulating the hit level response.  Geant simulates energy deposition in a block directly.  The gain enters when one tries to model the readout threshold of a cell because with the detector the readout threshold is applied in some flash ADC measurement of PMT pulse amplitude.  If one wants to convert that flash ADC amplitude into energy one needs the pedestals, gain, etc... but not some artificial gain, the real gain as measured by the data-based gain balancing algorithm.  This algorithm was carefully tuned on data to get the appropriate hit-level distributions in MC.

So there is no notion of a hit level gain that is relevant for MC unless someone wants to simulate a true gain that is different from the gain that the data were reconstructed with, but up to know our best knowledge of the gain is the gains we use for reconstruction.

There is an overall scale the is incorporated at the shower level that needs to be correct.  As Sean notes, that was tuned with a photon gun.  Your plots of pi0 vs. ring looks like (absent vertex issues) this scale may be high by 3-4 percent?  Ring 1 presumably has leakage into the beam hole and that is why it is systematically low.

If there are energy scale issues that is the right place to address it, not the block level gains.

Matt

**Comment by igjaegle** [comment]
The point is even if you are only using the Geant energy deposited in a cell, you will not get the pi0 mass at the correct position because the "gain" is not only correcting for the readout electronics which might be slightly different from one cell to another but also geometric effect and energy loss. Depending on how correct or wrong is the usage of the data gain (found during the gain calibration) in the MC simu., one might end up either correcting in the simulation for the geometric effect and energy loss for each different gain table or only using an additional correction factor for each ring (possibly cell) for all runs.

**Comment by mashephe** [comment]
I'm not aware any strong geometry dependence within the fiducial volume.  If there is we should discuss that first... and it wouldn't be obvious that a block level correction is a good route.


On Apr 27, 2020, at 8:21 AM, igjaegle <notifications@github.com<mailto:notifications@github.com>> wrote:



The point is even if you are only using the Geant energy deposited in a cell, you will not get the pi0 mass at the correct position because the "gain" is not only correcting for the readout electronics which might be slightly different from one cell to another but also geometric effect and energy loss. Depending on how correct or wrong is the usage of the data gain (found during the gain calibration) in the MC simu., one might end up either correcting in the simulation for the geometric effect and energy loss for each different gain table or only using an additional correction factor for each ring (possibly cell).

The data "gain" contains several corrections: readout and geometry.

**Comment by igjaegle** [comment]
The energy dependence correction per ring (w/o the energy dependence correction applied) show there is a geometry dependence (in the fiducial volume) which is not strong but it is not negligible either. See fig below for the simu. 

![image](https://user-images.githubusercontent.com/22524742/80387437-a42aac80-8876-11ea-9453-016ee91eba7d.png)
![image](https://user-images.githubusercontent.com/22524742/80387497-b73d7c80-8876-11ea-95e5-1c193ac3e74a.png)
![image](https://user-images.githubusercontent.com/22524742/80387564-c91f1f80-8876-11ea-93bc-849c5d30e3c9.png)

**Comment by sdobbs** [comment]
One additional note for clairification: there's currently no mechanism to apply a gain factor to the FCAL hits in mcsmear, so if we need an additional correction for something like a geometric effect, another table would be needed.   I would not reuse the existing table.

**Comment by igjaegle** [comment]
Could you point where the FCAL hits are transformed in mcsmear?

**Comment by sdobbs** [comment]
https://github.com/JeffersonLab/halld_sim/blob/fa6506f9745c4ba675ff9e84ab78af2923850054/src/programs/Simulation/mcsmear/FCALSmearer.cc#L151

**Comment by igjaegle** [comment]
Thank you, Sean. I see the data gain is used indirectly to estimate the threshold energy for each cell.

**Comment by sdobbs** [comment]
Yes, that's correct.

**Comment by igjaegle** [comment]
To summarize, the simulation is using directly the hit level energy deposited in each cell smeared by a Gaussian function to match the data resolution. As the simulated pi0 mean / pi0 PDG mass vs ring is varying between 1 to 4%, it appears a new table is needed in FCALSmearer.cc to align the simulated pi0 mean. I propose to call this new table mc_gain and to apply it after line 217.

**Comment by mashephe** [comment]
I recommend checking the response in MC with a photon gun instead of pi0.

Matt

**Comment by sdobbs** [comment]
I made a quick photon gun study, shooting a few thousand photons across the face of the FCAL.  It suggests we should take another look at the shower energy correction in simulation.
[e_mc_run61660.pdf](https://github.com/JeffersonLab/halld_sim/files/4542164/e_mc_run61660.pdf)

**Comment by igjaegle** [comment]
Could you clarify which table should be updated according to your study? shower_calib_piecewise?

**Comment by sdobbs** [comment]
Yes, that's correct.  It would be good to understand why this changed.

My guess is that we last tuned this calibration to hdgeant4, and then recently increased the energy scale factor based on hdgeant/hdgeant4 comparisons (if I remember correctly), which would basically explain the 3% increase in energy.

**Comment by igjaegle** [comment]
Yes, the increase, I found, was 2.4% from 0.976 to 1.0 (https://github.com/JeffersonLab/HDGeant4/issues/146). In a first step, I tried to correct only the energy dependence per ring but it is not working as well as in the data because the purpose of this correction is to correct for the energy dependence not align also all channels. Doing both at the same time complicate the procedure. For the first alignment, I believe, we will a new table e.g. mc_gain.

**Comment by rjones30** [comment]
That change was in response to a detailed study by Mark Dalton. Let's be
careful that we are not just going in circles here.
-Richard

**Comment by igjaegle** [comment]
No, that change was in response to my study. Mark D. determined the fudge factor for BCAL to match G3 and G4.
1/ There is a ring* dependence of the energy dependence correction
2/ The previous correction was applied to all rings but determined for the radius between ~20 and ~108 cm and did a fair job for 8 rings (ring 3 to 11) before this change to match G3 and G4. 

So even before this change, FCAL was not properly calibrated for simulation. NB: 

* With 5 cm width ring, FCAL is divided into 25 rings
