### ISSUE TITLE
Problems with recent hdgeant simulations

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/halld_sim#93]
Several people have reported crashes running mcsmear with the latest hdgeant version.
The culprit seems to be that hits are being generated with TOF bar=0, while the TOF bar numbering starts at 1.

This can be reproduced using the control.in file /w/halld-scifs17exp/home/sdobbs/particle_gun_request/crash/particle_gun.cfg

and running hdgeant with the command line 

hdgeant -xml=ccdb://GEOMETRY/main_HDDS.xml,run=51384

**Comment by rjones30** [comment]
Hello all,

I am trying to track down the errors people have been seeing with crashes
in mcsmear coming from hdgeant events with TOF bar=0 hits in the output.
This should not be happening, but I am unable to reproduce the exact
circumstances under which this is taking place. Please check your stdout
log from hdgeant and make sure it reports fetching+building+linking the
geometry from ccdb. I include below the relevant section from the stdout of
hdgeant from a recent run I took with "hdgeant
-xml=ccdb://GEOMETRY/main_HDDS.xml,run=51384". If this section does not
appear then your hdgeant executable is silently ignoring your -xml
commandline argument. If this is silently failing for you then I need to
chase this down.

On the other hand, if you are seeing this on-the-fly compile/build/link
geometry section in your stdout log (see below) and that part is working
then something is defective about the geometry you are fetching from ccdb.
To debug this further, I have added some checks in hitFTOF.c within the
hdgeant hits code. I am submitting a PR on github to add this code to the
master branch. As soon as this PR is executed, please update your hdgeant
build and try again. If there is something wrong with your ccdb geometry,
hdgeant should now exit with an error message instead of generating an
output hddm file with faulty tof hits in it.

-Richard Jones

==============================================================
Enabling dynamic geometry rendering
- - - - - - - - - - - - - - - - - - -

Please make sure the following environment variables are set:
   HDDS_HOME
   BMS_OSNAME
   CERN
   CERN_LEVEL

Generating FORTRAN from XML source ccdb://GEOMETRY/main_HDDS.xml,run=51384
JANA >>Created JCalibration object of type: JCalibrationCCDB
JANA >>Generated via: JCalibration using CCDB for MySQL and SQLite databases
JANA >>Run:51384
JANA >>URL: mysql://ccdb_user@hallddb.jlab.org/ccdb
JANA >>context: variation=mc
JANA >>comment: Variation for simulations with data conditions
GEOMETRY/BarrelEMcal_HDDS.xml
GEOMETRY/BeamLine_HDDS.xml
GEOMETRY/CentralDC_HDDS.xml
GEOMETRY/CerenkovCntr_HDDS.xml
GEOMETRY/ComptonEMcal_HDDS.xml
GEOMETRY/cpp_HDDS.xml
GEOMETRY/DIRC_HDDS.xml
GEOMETRY/DIRC_HDDS_original.xml
GEOMETRY/ForwardDC_HDDS.xml
GEOMETRY/ForwardEMcal_HDDS.xml
GEOMETRY/ForwardMWPC_HDDS.xml
GEOMETRY/ForwardTOF_HDDS.xml
GEOMETRY/GapEMcal_HDDS.xml
GEOMETRY/HDDS-1_0.xsd
GEOMETRY/HDDS-1_1.xsd
GEOMETRY/main_HDDS.xml
GEOMETRY/Material_HDDS.xml
GEOMETRY/PairSpect_HDDS.xml
GEOMETRY/Regions_HDDS.xml
GEOMETRY/Solenoid_HDDS.xml
GEOMETRY/StartCntr_HDDS.xml
GEOMETRY/TargetCPP_HDDS.xml
GEOMETRY/Target_HDDS.xml
GEOMETRY/UpstreamEMveto_HDDS.xml
s$HDDS_HOME/$BMS_OSNAME/bin/hdds-geant .hdds_tmp_lRDPVm/main_HDDS.xml >
tmp.F

Compiling FORTRAN into shared object ...
gfortran -shared -fPIC -o tmp.so -I$CERN/$CERN_LEVEL/include tmp.F

Attaching shared object ...
Linking routines ...
  ... linked hddsgeant3_
  ... linked md5geom_
  ... linked guplsh_
  ... linked gufld_
  ... linked getoptical_
  ... linked getcolumn_
  ... linked getlayer_
  ... linked getmap_
  ... linked getmodule_
  ... linked getpackage_
  ... linked getplane_
  ... linked getring_
  ... linked getrow_
  ... linked getsector_
  ... linked getpaired_row_

Geometry loaded successfully
==============================================================

**Comment by sdobbs** [comment]
Hi, after Richards latest changes, I'm mysteriously no longer able to reproduce the problem.  Maybe we should tag a new version for some wider scale tests?

**Comment by markito3** [comment]
I'll try to get to tagging and building a version sometime soon...

**Comment by sdobbs** [comment]
This problem hasn't shown up in awhile, so I will close this issue.
